const mongoose = require('mongoose');
const Book = require('./models/Book');

const newBooks = [
  { legacyId: 101, title: "1984", author: "George Orwell", description: "Among the seminal texts of the 20th century, Nineteen Eighty-Four is a rare work that grows more haunting as its futuristic purgatory becomes more real. Published in 1949, the book offers political satirist George Orwell's nightmarish vision of a totalitarian, bureaucratic world.", content: "Part 1, Chapter 1: It was a bright cold day in April, and the clocks were striking thirteen...", totalPages: 328, coverUrl: "https://covers.openlibrary.org/b/id/15330132-L.jpg", pdfUrl: "https://www.planetebook.com/free-ebooks/1984.pdf", isbn: "978-0451524935", publicationYear: 1949, category: "Dystopian", isDeleted: false, isAvailable: true },
  { legacyId: 102, title: "The Great Gatsby", author: "F. Scott Fitzgerald", description: "The story of the mysteriously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan, of lavish parties on Long Island at a time when The New York Times noted gin was the national drink and sex the national obsession.", content: "Chapter 1: In my younger and more vulnerable years my father gave me some advice...", totalPages: 218, coverUrl: "https://covers.openlibrary.org/b/id/14358872-L.jpg", pdfUrl: "https://www.planetebook.com/free-ebooks/the-great-gatsby.pdf", isbn: "978-0743273565", publicationYear: 1925, category: "Classic", isDeleted: false, isAvailable: true },
  { legacyId: 103, title: "Pride and Prejudice", author: "Jane Austen", description: "Since its immediate success in 1813, Pride and Prejudice has remained one of the most popular novels in the English language. Jane Austen called this brilliant work her own darling child and its vivacious heroine, Elizabeth Bennet, as delightful a creature as ever appeared in print.", content: "Chapter 1: It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.", totalPages: 432, coverUrl: "https://covers.openlibrary.org/b/id/14541539-L.jpg", pdfUrl: "https://www.planetebook.com/free-ebooks/pride-and-prejudice.pdf", isbn: "978-1503290563", publicationYear: 1813, category: "Romance", isDeleted: false, isAvailable: true },
  { legacyId: 104, title: "Frankenstein", author: "Mary Shelley", description: "Mary Shelley began writing Frankenstein when she was only eighteen. At once a Gothic thriller, a passionate romance, and a cautionary tale about the dangers of science, Frankenstein tells the story of committed science student Victor Frankenstein.", content: "Letter 1: To Mrs. Saville, England. You will rejoice to hear that no disaster has accompanied the commencement of an enterprise...", totalPages: 280, coverUrl: "https://covers.openlibrary.org/b/id/13010793-L.jpg", pdfUrl: "https://www.planetebook.com/free-ebooks/frankenstein.pdf", isbn: "978-0486282114", publicationYear: 1818, category: "Horror", isDeleted: false, isAvailable: true },
  { legacyId: 105, title: "Dracula", author: "Bram Stoker", description: "When Jonathan Harker visits Transylvania to help Count Dracula with the purchase of a London house, he makes a series of horrific discoveries about his client. Soon afterwards, various bizarre incidents unfold in England.", content: "Chapter 1: Jonathan Harker's Journal. 3 May. Bistritz.—Left Munich at 8:35 P. M., on 1st May...", totalPages: 416, coverUrl: "https://covers.openlibrary.org/b/id/14603912-L.jpg", pdfUrl: "https://www.planetebook.com/free-ebooks/dracula.pdf", isbn: "978-0486411095", publicationYear: 1897, category: "Horror", isDeleted: false, isAvailable: true },
  { legacyId: 106, title: "Alice's Adventures in Wonderland", author: "Lewis Carroll", description: "In 1862 Charles Lutwidge Dodgson, a shy Oxford mathematician with a stammer, created a story about a little girl tumbling down a rabbit hole. Thus began the immortal adventures of Alice.", content: "Chapter 1: Down the Rabbit-Hole. Alice was beginning to get very tired of sitting by her sister on the bank...", totalPages: 200, coverUrl: "https://covers.openlibrary.org/b/id/14588825-L.jpg", pdfUrl: "https://www.planetebook.com/free-ebooks/alices-adventures-in-wonderland.pdf", isbn: "978-1503222687", publicationYear: 1865, category: "Fantasy", isDeleted: false, isAvailable: true },
  { legacyId: 107, title: "The Adventures of Sherlock Holmes", author: "Arthur Conan Doyle", description: "A collection of twelve short stories featuring Arthur Conan Doyle's legendary detective, Sherlock Holmes. The stories are not in chronological order, and the only characters common to all twelve are Holmes and Dr. Watson.", content: "Adventure 1: A Scandal in Bohemia. To Sherlock Holmes she is always THE woman...", totalPages: 305, coverUrl: "https://covers.openlibrary.org/b/id/14540455-L.jpg", pdfUrl: "https://www.planetebook.com/free-ebooks/the-adventures-of-sherlock-holmes.pdf", isbn: "978-1505297126", publicationYear: 1892, category: "Mystery", isDeleted: false, isAvailable: true },
  { legacyId: 108, title: "Moby-Dick", author: "Herman Melville", description: "First published in 1851, Melville's masterpiece is, in Elizabeth Hardwick's words, the greatest novel in American literature. The saga of Captain Ahab and his relentlessly hunted whale.", content: "Chapter 1: Loomings. Call me Ishmael...", totalPages: 720, coverUrl: "https://covers.openlibrary.org/b/id/14592015-L.jpg", pdfUrl: "https://www.planetebook.com/free-ebooks/moby-dick.pdf", isbn: "978-1503280786", publicationYear: 1851, category: "Adventure", isDeleted: false, isAvailable: true },
  { legacyId: 109, title: "A Tale of Two Cities", author: "Charles Dickens", description: "After eighteen years as a political prisoner in the Bastille, the ageing Doctor Manette is finally released and reunited with his daughter in England. There the lives of two very different men become enmeshed through their love for Lucie Manette.", content: "Book 1, Chapter 1: The Period. It was the best of times, it was the worst of times...", totalPages: 489, coverUrl: "https://covers.openlibrary.org/b/id/14539656-L.jpg", pdfUrl: "https://www.planetebook.com/free-ebooks/a-tale-of-two-cities.pdf", isbn: "978-0486406510", publicationYear: 1859, category: "Historical Fiction", isDeleted: false, isAvailable: true },
  { legacyId: 110, title: "Jane Eyre", author: "Charlotte Brontë", description: "Orphaned as a child, Jane has felt an outcast her whole young life. Her courage is tested once again when she arrives at Thornfield Hall, where she has been hired by the brooding, proud Edward Rochester to care for his ward.", content: "Chapter 1: There was no possibility of taking a walk that day...", totalPages: 532, coverUrl: "https://covers.openlibrary.org/b/id/14539659-L.jpg", pdfUrl: "https://www.planetebook.com/free-ebooks/jane-eyre.pdf", isbn: "978-0141441146", publicationYear: 1847, category: "Gothic Fiction", isDeleted: false, isAvailable: true },
  { legacyId: 111, title: "Crime and Punishment", author: "Fyodor Dostoevsky", description: "Raskolnikov, a destitute and desperate former student, wanders through the slums of St Petersburg and commits a random murder without remorse or regret. He imagines himself to be a great man, a Napoleon.", content: "Part 1, Chapter 1: On an exceptionally hot evening early in July a young man came out of the garret...", totalPages: 671, coverUrl: "https://covers.openlibrary.org/b/id/14441584-L.jpg", pdfUrl: "https://www.planetebook.com/free-ebooks/crime-and-punishment.pdf", isbn: "978-0486415871", publicationYear: 1866, category: "Psychological Fiction", isDeleted: false, isAvailable: true },
  { legacyId: 112, title: "Wuthering Heights", author: "Emily Brontë", description: "The story of the doomed love between Catherine Earnshaw and the dark, brooding Heathcliff. Their passion is as wild and destructive as the moors they wander.", content: "Chapter 1: 1801. I have just returned from a visit to my landlord—the solitary neighbour that I shall be troubled with...", totalPages: 416, coverUrl: "https://covers.openlibrary.org/b/id/14539665-L.jpg", pdfUrl: "https://www.planetebook.com/free-ebooks/wuthering-heights.pdf", isbn: "978-0141439556", publicationYear: 1847, category: "Gothic Fiction", isDeleted: false, isAvailable: true },
  { legacyId: 113, title: "Great Expectations", author: "Charles Dickens", description: "The orphan Pip's terrifying encounter with an escaped convict on the Kent marshes, and his mysterious summons to the house of Miss Havisham, change his life forever.", content: "Chapter 1: My father's family name being Pirrip, and my Christian name Philip, my infant tongue could make of both names nothing longer or more explicit than Pip.", totalPages: 544, coverUrl: "https://covers.openlibrary.org/b/id/14539668-L.jpg", pdfUrl: "https://www.planetebook.com/free-ebooks/great-expectations.pdf", isbn: "978-0141439563", publicationYear: 1861, category: "Classic", isDeleted: false, isAvailable: true },
  { legacyId: 114, title: "The Picture of Dorian Gray", author: "Oscar Wilde", description: "Enthralled by his own exquisite portrait, Dorian Gray exchanges his soul for eternal youth and beauty. Influenced by his friend Lord Henry Wotton, he is drawn into a corrupt double life.", content: "Chapter 1: The studio was filled with the rich odour of roses, and when the light summer wind stirred amidst the trees...", totalPages: 254, coverUrl: "https://covers.openlibrary.org/b/id/14539671-L.jpg", pdfUrl: "https://www.planetebook.com/free-ebooks/the-picture-of-dorian-gray.pdf", isbn: "978-0141439570", publicationYear: 1890, category: "Philosophical Fiction", isDeleted: false, isAvailable: true },
  { legacyId: 115, title: "Les Misérables", author: "Victor Hugo", description: "Introducing one of the most famous characters in literature, Jean Valjean—the noble peasant imprisoned for stealing a loaf of bread—Les Misérables ranks among the greatest novels of all time.", content: "Volume 1, Book 1, Chapter 1: In 1815, M. Charles-Francois-Bienvenu Myriel was Bishop of D—.", totalPages: 1463, coverUrl: "https://covers.openlibrary.org/b/id/14539675-L.jpg", pdfUrl: "https://www.planetebook.com/free-ebooks/les-miserables.pdf", isbn: "978-0451419439", publicationYear: 1862, category: "Historical Fiction", isDeleted: false, isAvailable: true },
  { legacyId: 116, title: "War and Peace", author: "Leo Tolstoy", description: "Broadly focusing on Napoleon's invasion of Russia in 1812 and following three of the most well-known characters in literature: Pierre Bezukhov, the illegitimate son of a count who is fighting for his inheritance.", content: "Book 1, Chapter 1: 'Well, Prince, so Genoa and Lucca are now just family estates of the Buonapartes.'", totalPages: 1225, coverUrl: "https://covers.openlibrary.org/b/id/14539678-L.jpg", pdfUrl: "https://www.planetebook.com/free-ebooks/war-and-peace.pdf", isbn: "978-1400079988", publicationYear: 1869, category: "Historical Fiction", isDeleted: false, isAvailable: true },
  { legacyId: 117, title: "The Brothers Karamazov", author: "Fyodor Dostoevsky", description: "Dostoevsky's last and greatest novel is a magnificent tale of patricide and fraternal rivalry, featuring the fierce and rebellious Dmitri, the rational Ivan, and the spiritual Alyosha.", content: "Part 1, Book 1, Chapter 1: Alexey Fyodorovitch Karamazov was the third son of Fyodor Pavlovitch Karamazov...", totalPages: 796, coverUrl: "https://covers.openlibrary.org/b/id/14539681-L.jpg", pdfUrl: "https://www.planetebook.com/free-ebooks/the-brothers-karamazov.pdf", isbn: "978-0374528379", publicationYear: 1880, category: "Philosophical Fiction", isDeleted: false, isAvailable: true },
  { legacyId: 118, title: "The Awakening", author: "Kate Chopin", description: "First published in 1899, The Awakening is widely seen as one of the first American novels that focuses on women's issues without condescension. It is also widely seen as a landmark work of early feminism.", content: "Chapter 1: A green and yellow parrot, which hung in a cage outside the door, kept repeating over and over...", totalPages: 195, coverUrl: "https://covers.openlibrary.org/b/id/14539684-L.jpg", pdfUrl: "https://www.planetebook.com/free-ebooks/the-awakening.pdf", isbn: "978-0486277868", publicationYear: 1899, category: "Feminist Fiction", isDeleted: false, isAvailable: true },
  { legacyId: 119, title: "Metamorphosis", author: "Franz Kafka", description: "The story of a young man who, transformed overnight into a giant beetle-like insect, becomes an object of disgrace to his family, an outsider in his own home, a quintessentially alienated man.", content: "Chapter 1: One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin.", totalPages: 201, coverUrl: "https://covers.openlibrary.org/b/id/14539687-L.jpg", pdfUrl: "https://www.planetebook.com/free-ebooks/metamorphosis.pdf", isbn: "978-1505297133", publicationYear: 1915, category: "Absurdist Fiction", isDeleted: false, isAvailable: true },
  { legacyId: 120, title: "The Odyssey", author: "Homer", description: "Literature's grandest evocation of life's journey, at once an ageless human story and an individual test of moral endurance. Homer's epic tale of Odysseus and his ten-year journey home after the Trojan War.", content: "Book 1: Tell me, O muse, of that ingenious hero who travelled far and wide after he had sacked the famous town of Troy...", totalPages: 541, coverUrl: "https://covers.openlibrary.org/b/id/14539690-L.jpg", pdfUrl: "https://www.planetebook.com/free-ebooks/the-odyssey.pdf", isbn: "978-0140268867", publicationYear: 1900, category: "Epic Poetry", isDeleted: false, isAvailable: true }
];

const dotenv = require('dotenv');
dotenv.config();

mongoose.connect(process.env.MONGODB_URI)
  .then(async () => {
    // Check if books already exist to avoid duplicates
    const count = await Book.countDocuments();
    if (count > 0) {
      console.log(`⚠️ Books already exist (${count}). Clearing collection first...`);
      await Book.deleteMany({});
    }

    const result = await Book.insertMany(newBooks);
    console.log(`✅ Successfully added ${result.length} books to MongoDB Atlas!`);
    console.log('\nAdded books:');
    result.forEach(b => console.log(`  • ${b.title} by ${b.author} (${b.category})`));
    const totalBooks = await Book.countDocuments({ isAvailable: true });
    console.log(`\n📚 Total available books now: ${totalBooks}`);
    process.exit(0);
  })
  .catch(e => {
    console.error('❌ Connection or Insertion Error:', e.message);
    process.exit(1);
  });
